"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Загружаем переменные из .env (для локальной разработки)
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# =====================
# SECURITY (Безопасность)
# =====================

# Читаем ключ из переменной окружения, если его нет — используем запасной (только для теста)
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-dev-key-123")

# DEBUG будет True только если в окружении прямо написано 'True'
# На сервере (Render) мы поставим 'False'
DEBUG = os.getenv("DEBUG", "False") == "True"

# В ALLOWED_HOSTS добавляем локальные адреса и адрес твоего будущего сайта
ALLOWED_HOSTS = ["*"] # Для учебного деплоя оставим так, либо добавь конкретный .onrender.com

# =====================
# APPLICATIONS
# =====================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Твои приложения
    'store',
    'reviews',
    'promotions',
]

# =====================
# MIDDLEWARE
# =====================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise должен быть сразу после SecurityMiddleware для работы CSS в облаке
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =====================
# URLS & TEMPLATES
# =====================

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# =====================
# DATABASE
# =====================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# =====================
# PASSWORD VALIDATION
# =====================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =====================
# INTERNATIONALIZATION
# =====================

LANGUAGE_CODE = 'ru-ru' # Поменял на русский
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =====================
# STATIC FILES (Важно для деплоя!)
# =====================

STATIC_URL = '/static/'

# Папка со статикой в корне проекта
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Папка, куда соберутся файлы для сервера
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Оптимизация WhiteNoise (сжатие файлов для быстрой загрузки)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'